kind: Job
apiVersion: batch/v1
metadata:
  name: pvmigrate
  namespace: default
spec:
  completions: 1
  template:
    spec:
      serviceAccountName: pvmigrate
      restartPolicy: Never
      containers:
        - name: pvmigrate
          image: ttl.sh/build-test/pvmigrate:latest
          command: [ "/pvmigrate" ]
          args: [ "--source-sc", "int-source", "--dest-sc", "int-dest" ]
